let myDates=new Date()
// console.log(myDates.toLocaleDateString())
// console.log(myDates.getDate())
// console.log(myDates.getDay())
// console.log(myDates.getFullYear())
// console.log(myDates.getUTCDate())
// console.log(myDates.toString())
let myCreatedDate = new Date(2023,10,27)
console.log(myCreatedDate.toLocaleDateString())
console.log(myCreatedDate.toDateString())

console.log(myDates.getTime())
console.log(myDates.getMonth())