// console.log(2+2)
// console.log(2-2)
// console.log(2*2)
// console.log(2/2)
// console.log(5%2)
// console.log(2**3)
// let str1='Aman'
// let str2=' Makwana'
// console.log(str1+str2)
// console.log('Null Comapre with 0')
// console.log(null>0)
// console.log(null==0)
// console.log(null>=0)
// console.log(null<=0)
// console.log(null<0)
// console.log('Undefiened compare with 0')
// console.log(undefined>0)
// console.log(undefined==0)
// console.log(undefined>=0)
// console.log(undefined<=0)
// console.log(undefined<0)

console.log('Undefined and null comparision')
console.log(undefined>null)
console.log(undefined==null)
console.log(undefined>=null)
console.log(undefined<=null)
console.log(undefined<null)